---
title: Initiation à l'analyse de données avec R 
author: Camille Pelletier<br>Laurence-Olivier M. Foisy
institute: Université Laval
format:
  revealjs:
    mermaid: 
      theme: dark
    theme: simple
    logo: img\logo_CLESSN.png
    footer: "Analyse de données avec R"
    transition: slide
    transition-speed: fast
---

## Plan de l'atelier

### 9h à 12h 
- Qu'est-ce que l'analyse de données?
- Pourquoi R?
- Introduction à R et RStudio


### 12h à 15h
- Atelier libre avec des mentors de la CLESSN 
- Exercices avec R

## Objectifs de l'atelier{.smaller}

- Introduire R pour l'analyse de données.
  - Les dataframes
  - Les fonctions
  - Les packages 
  - Les graphiques
  - Les statistiques

> Le but est que vous puissiez sortir d'ici avec une compréhension de base de R et que vous soyez capable d'aller chercher des ressources pour continuer à apprendre.

## Pourquoi suivre cet atelier?

- Comprendre le monde autour de nous à travers des données
- Compétences recherchées sur le marché du travail
- Base solide pour la recherche académique
- Comprendre la pertinence du logiciel de traitement de données R
- Obtenir des outils pour dédramatiser la science des données

## Pourquoi cet atelier?

#### Comprendre le monde autour de nous à travers des données

- Les données sont partout, mais pas nécessairement intelligibles.

> L'analyse de données permet de comprendre ces données, et donc de mieux comprendre le monde qui nous entoure.


:::{.notes}
Tout est des données autours de nous. L'analyse de données permet de simplifier la réalité pour comprendre et expliquer des phénomènes ou des comportements dans le monde qui nous entoure.

Pouvoir de prédiction: prédire comment certaines variables ou facteurs influencent d’autres variables ou événements. 
:::

## Qu'est-ce que l'analyse de données?

- Le but est de rendre les données compréhensibles
- Il y a des millions de données qui sont générées chaque jour
- L'analyse de données permet de comprendre ces données et donc de comprendre le monde qui nous entoure

## Pourquoi R?

Expliquer pourquoi R est un outil de choix pour l'analyse de données.
Pourquoi on choisi R versus d'autres outils comme Stata et SPSS.

- Open source
- Packages
- Reproductibilité
- Très utilisé en science sociale

## Pourquoi R?

### Open source

- Gratuit
- Collaboratif
- Communauté active
- Adapté aux besoins des utilisateurs

## Pourquoi R?

### Packages

- Offre une extension des fonctionnalités de base presque infinie
- Peux répondre à des besoins très spécifiques
- 21,744 packages sur CRAN
- Beaucoup plus sur GitHub

## Pourquoi R?

### Reproductibilité

- Rendre les analyses reproductibles
- Permet de partager les analyses
- Permet de retracer les erreurs
- Partager le code

## Pourquoi R?

### Très utilisé en science sociale

- Beaucoup de ressources
- Beaucoup de tutoriels orientés vers la science sociale
- Important d'être dans le même langage que les autres chercheurs

## Présentation de la CLESSN

Présenter nos travauxe et la variété de projets menés avec R

Datagotchi, les histoires, les articles, les shiny, etc.

- Datagotchi
- Shiny catalogue
- GPT
- Analyse textuelle

## Datagotchi

- Application Web de sondage ludique

Les données sont analysées en R

<!--NOTE: Mettre un beau graphique?-->

## Shiny Catalogue

Un élève de la CLESSN a crée un catalogue avec tous nos données en Shiny, un architecture web programmable en R

## Les LLM

R permet d'intéragir avec les LLM. De mélanger les données avec la puissance des LLM permet de pousser l'analyse de données plus loin.

## Analyse textuelle

R permet de faire de données qualitatives

## Installer R et RStudio

- C'est quoi la différence entre R et RStudio?
- R est le moteur, RStudio est l'interface
- RStudio facilite l'utilisation de R
- RStudio est un IDE (Integrated Development Environment)

## Une fois dans RStudio

Les quatre fenêtres de RStudio
Comment écrire du code dans RStudio

- Console
- Environment
- Files
- Plots

## Concepts importants

Vous devez savoir où vous êtes dans votre ordinateur pour pouvoir importer des données ou exporter des graphiques. 
Votre R est toujours ouvert dans un dossier, vous devez savoir où il est pour pouvoir importer des données. 

Savoir ce que vous voulez faire avant de commencer à écrire du code. La plus grosse erreur est de commencer à écrire du code sans savoir ce que vous voulez faire.

## Importer des données

Les données sont souvent dans des fichiers Excel, CSV, ou autres.
Il est important de savoir comment importer ces données dans R.

## L'analyse descriptive des données

- Qu'est-ce que c'est?

- table()
- names()
- hist()
- summary()

## Représentation graphique des données

- Importance de la visualisation
  - Qu'est-ce qu'une bonne visualisation graphique?
  - Tufte

- ggplot2
  - Les layers

- Shiny
  - Créer des applications interactives

## Analyse statistique

- Les régressions
- Les tests statistiques
- Les modèles

## Tableaux de régression

- modelsummary

## Ressources

Quoi faire quand ça ne fonctionne pas?

- ChatGPT
- Réessayer ChatGPT
- La documentation de R
- Google

## Conclusion
